language: java
dist: trusty
deploy:
  provider: releases
  api_key:
    secure: VRjHwPRhdKZk0jh4kaVizYvvHlam3IRarysLm3rL5gupCYK+wXZay0e8Qud3Sx07yJ+IFOFpa77gHiLWsQo2STHBNCQvB/biVl71KXBNhJSk5tTAiiZS8PmZBMaHzdwRPmgpuXSl1yaMxhynxKCey2A4+nPggCS7SpU1hgADyNh+6wux1UooIHgBzUhO9io8xnn/DvAl0wzUqvwMnCaeAyLXLVOqU/32IDYGIKaQCVbZFDF01F606KsDYSnLNWDuDqS0TcMN8rl/hiPTsK7S3MG6eGFDmqN2ok+P8ds4R5dkM1lGPa5QJ1o7F3suOduJgHbAzuxo4esVfoitl9mvB6fTTxqKPp0RpU4nWg5Ab9CYkPxubsIOQTygl1BX0ybqUnMo1E5ZsY1nZb28xgDeZyLfl9QCUD+8+5vW6j/nXS6/2098VuWqJ/02CEoDuXcKrFgCs6ClhqqSCRAuZkALzwOGaIQHDcGQ7ZKDqnu49ZA7a6PqQtNZNThDB9EaTNOO7GgBArVw2c+VS51XIl2x8nFFUCS+HtoMVh1w0+w7RvI0oxCxfVfvWu6PG91TTpJg62yBy9Y4geJFgB47mehnhg0Gx0CWC3DbwdVGq8h/aTHMI8CWvgnMpxF4rmD7adnGZmYLf4s2wDcWILj9kP/+9y5XhP2j8ip3e+oQe+2o+b4=
  file-glob: true
  file: '*/target/PlayerIPAPI-*.jar'
  on:
    repo: egg82/PlayerIPAPI
addons:
  sonarcloud:
    organization: 'egg82-github'
    token:
      secure: "gh5F8aQiFt3eoZOTSHYyZfxMornYNcMr47OZ/vVw6phugOxJ4idXKROqkG9HPgtNOWC6SEijLv4wF2MB/TIBkQ4BaDIX4ptGkWm6YVhh/g2g04tLZu0npFKaRpw45GX4ybgIonUSQp1lRg92zG2oLSEBDRaPPyoqE28OUXSE71q1gbeUvrb59ftwASLexed2vOBVqnrsL/M2za7pk03xm3OTOOGydyIMQLauvjxv9qeN5urDUG/ZdUgRWTORit8YaT1zGYGBK4BYRe2qOPB+cJUwr9+biTmjX+r1tQHJGMyNOMPPoMq8aOiWinN24eOD4c+Or1ShCIYbtTiVkJO5jzryXh1zyVNQrzM/S+eBfQcOXZ6KrEriT1v4F0dhOCK5s53jTScOEyVZH8/u2PFloX7bWmCIeBxuQ+rzz8ybem0ZodhbtORp/RiBoIxmkE6PtiuZU2PEDa906jsndhRSVXa0pmNn7uJtqgPFLNqB4juu/erucBQeOFsLXX4FWXwLZiIpUl1YUoFgfaDxzvu6ZnJahVyFt9JKtoCOiQUzjtlQEwyZ1sQ16sClBnhUZMZIN+sSoVzNb23BnskaSiO0efVbo/aRD23lebFE+gM0eEt3at+NtptUTH3/8rX+01CSI21u/cBcDSPc15xFBphZuNBc4AdQEABvB+uWJ0Yong8="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar