name: PlayerIPAPI
main: me.egg82.ipapi.PlayerIPAPI
version: 1.2.8
author: egg82
description: A nice API that allows for VERY fast alt detection and Essentials-like /seen lookups
commands:
  ipapireload:
    description: Reloads the plugin
    usage: /ipapireload
    permission: ipapi.admin