name: PlayerIPAPI
main: me.egg82.ipapi.PlayerIPAPI
version: 1.1.4
author: egg82
description: API that logs player/IP combos and allows for a nice developer API to easily retrieve that data
commands:
  ipapireload:
    description: Reloads the plugin
    usage: /ipapireload
    permission: ipapi.admin