# This is the backing data for everything
# SQL is used as long-term storage and cross-network updates every few seconds
# Try to use an SQL source each server has access to, if possible
# You may choose to use MySQL or SQLite
# An SQL database of SOME description is required
sql:
  # The type of database to use. May be either MySQL or SQLite
  type: 'sqlite'
  # Number of connections to use. Cannot be lower than 1
  # Recommended 2+ for parallel queries for non-Redis servers
  # If using Redis, set this to 2+ on hubs and 1 on servers
  threads: 2
  mysql:
    address: '127.0.0.1'
    port: 3306
    user: ''
    pass: ''
    database: 'avpn'
  sqlite:
    file: 'avpn.db'

# Redis is used as a cache so lookups can be VERY fast
# This is used in both the expensive and non-expensive lookups
# It also provides the ability to push instant updates across the network
# Redis is entirely optional
redis:
  enabled: false
  address: ''
  port: 6379
  pass: ''

# Messaging is used to push instant commands across the network
# If you don't have/use Redis you can use this to update faster than SQL
# Even if you use Redis, this can be used as a backup source
# Messaging is entirely optional
messaging:
  # The type of messaging to use
  # Values can be 'bungee' ('default') or 'rabbit'
  # If 'default' or 'bungee' is selected, please be sure to use PlayerIPAPI for BungeeCord!
  type: 'bungee'
  # Values to fill in if using Rabbit messaging
  rabbit:
    address: ''
    port: 5672
    user: 'guest'
    pass: 'guest'

# The amount of time before in-memory caches expire after non-use
# This prevents many sequential lookups from using more expensive networking constantly
cacheTime: '1minute'
# When true, logs some extra output to the console so you can see if/why things might be failing
debug: false

stats:
  # Whether or not to send anonymous usage statistics to bStats
  # True: Send anonymous stats; let the author know how well the plugin is doing and how it's used!
  # False: Do not send stats and make the author sad :(
  usage: true
  # Whether or not to send anonymous errors to the author
  # True: Send errors anonymously to Rollbar and/or GameAnalytics so the author can fix them!
  # False: Do not send errors and wonder why any bugs you encounter haven't beeen fixed
  errors: true

update:
  # Whether or not to automatically check for updates and notify the console if found
  check: true
  # Whether or not to notify players with the avpn.admin permission node
  notify: true

# Config version, no touchy plz
version: 3.0